# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConstraintTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityCharFieldValues',
            fields=[
                ('fieldDataId', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityDataMappings',
            fields=[
                ('dataMappingId', models.AutoField(primary_key=True, serialize=False)),
                ('entityDataId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityDateFieldValues',
            fields=[
                ('fieldDataId', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DateTimeField()),
                ('entityDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityDataMappings')),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityFieldConstraints',
            fields=[
                ('constraintId', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityIntFieldValues',
            fields=[
                ('fieldDataId', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('entityDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityDataMappings')),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityTypeFields',
            fields=[
                ('fieldId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntityTypes',
            fields=[
                ('entityTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('clientId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('noOfUDFS', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='riskentitytypefields',
            name='entityTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskentitytypefields', to='riskMgr.RiskEntityTypes'),
        ),
        migrations.AddField(
            model_name='riskentitytypefields',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.FieldTypes'),
        ),
        migrations.AddField(
            model_name='riskentityintfieldvalues',
            name='fieldId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityTypeFields'),
        ),
        migrations.AddField(
            model_name='riskentityfieldconstraints',
            name='fieldId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskentityfieldconstraints', to='riskMgr.RiskEntityTypeFields'),
        ),
        migrations.AddField(
            model_name='riskentityfieldconstraints',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskentityfieldconstraints', to='riskMgr.FieldConstraintTypes'),
        ),
        migrations.AddField(
            model_name='riskentitydatefieldvalues',
            name='fieldId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityTypeFields'),
        ),
        migrations.AddField(
            model_name='riskentitydatamappings',
            name='entityTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityTypes'),
        ),
        migrations.AddField(
            model_name='riskentitycharfieldvalues',
            name='entityDataId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityDataMappings'),
        ),
        migrations.AddField(
            model_name='riskentitycharfieldvalues',
            name='fieldId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskMgr.RiskEntityTypeFields'),
        ),
    ]
